apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-gitlab-cicd
  labels:
    app: test-gitlab-cicd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-gitlab-cicd
  
  # Pod template
  template:
    metadata:
      labels:
        app: test-gitlab-cicd
    spec:
      containers:
        - name: test-gitlab-cicd
          image: docker.io/library/nginx:_VERSION_
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "12Mi"
              cpu: "51m"
            limits:
              memory: "25Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      imagePullSecrets:
        - name: gitlabcicd
---
apiVersion: v1
kind: Service
metadata:
  name: test-gitlab-cicd
  labels:
    app: test-gitlab-cicd
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
      app: test-gitlab-cicd
